-- require("core.plugin_config.integrated_visual_aids.alpha")
require("core.plugin_config.integrated_visual_aids.lualine")
require("core.plugin_config.integrated_visual_aids.nvim-ufo")
require("core.plugin_config.integrated_visual_aids.indent-blankline")
require("core.plugin_config.integrated_visual_aids.dashboard")
