# preload = $HOME/Images/rice_wallpaper/flower_1.png
preload = $HOME/Images/rice_wallpaper/flower_2.jpg
# preload = $HOME/Images/rice_wallpaper/nord-shards.png

wallpaper {
	monitor = DP-2
	path = $HOME/Images/rice_wallpaper/flower_2.jpg
}
wallpaper {
	monitor = HDMI-A-1
	path = $HOME/Images/rice_wallpaper/flower_2.jpg
}

# Fallback
wallpaper[]:path = $HOME/Images/rice_wallpaper/flower_2.jpg

ipc = true
splash = false
